# Generated by Django 3.0.3 on 2020-05-01 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_id', models.IntegerField()),
                ('post_header', models.CharField(max_length=50, unique=True)),
                ('post_content', models.CharField(max_length=50, unique=True)),
                ('post_author', models.CharField(max_length=200, null=True)),
                ('post_created_date', models.DateField(null=True)),
            ],
        ),
    ]
