# Generated by Django 3.0.3 on 2020-05-01 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_updated_date',
            field=models.DateField(null=True),
        ),
    ]
