# Generated by Django 3.0.3 on 2020-05-01 15:09

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_header', models.CharField(max_length=100, unique=True)),
                ('post_Name', models.CharField(max_length=100, null=True, unique=True)),
                ('post_content', models.CharField(max_length=1000, null=True)),
                ('post_author', models.CharField(max_length=50, null=True)),
                ('post_created_dt', models.DateTimeField(default=datetime.datetime.now, null=True)),
                ('post_updated_dt', models.DateTimeField(default=datetime.datetime.now, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_review', models.CharField(max_length=50, unique=True)),
                ('post_reviewed_by', models.CharField(max_length=50, unique=True)),
                ('post_reviewed_dt', models.DateTimeField(default=datetime.datetime.now, null=True)),
                ('post_header', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.Post', to_field='post_header')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_category_name', models.CharField(max_length=50, null=True)),
                ('post_category_description', models.CharField(max_length=200, null=True)),
                ('post_category_created_dt', models.DateTimeField(default=datetime.datetime.now, null=True)),
                ('post_category_updated_dt', models.DateTimeField(default=datetime.datetime.now, null=True)),
                ('post_header', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.Post', to_field='post_header')),
            ],
        ),
    ]
