# Generated by Django 3.0.3 on 2020-05-08 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0009_auto_20200508_1348'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_short_desc',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
