# Generated by Django 3.0.3 on 2020-05-06 06:36

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_header', models.CharField(max_length=50, unique=True)),
                ('course_name', models.CharField(max_length=50, unique=True)),
                ('course_category', models.CharField(max_length=50, unique=True)),
                ('course_author', models.CharField(max_length=50, null=True)),
                ('course_description', models.CharField(max_length=5000, null=True)),
                ('created_dt', models.DateTimeField(default=datetime.datetime.now, null=True)),
                ('updated_dt', models.DateTimeField(default=datetime.datetime.now, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_comment', models.CharField(max_length=500)),
                ('reviewed_by', models.CharField(max_length=50, unique=True)),
                ('course_video_quality', models.CharField(max_length=50, unique=True)),
                ('course_content_quality', models.CharField(max_length=50, unique=True)),
                ('course_engagging_quality', models.CharField(max_length=50, unique=True)),
                ('course_sound_quality', models.CharField(max_length=50, unique=True)),
                ('star_rating', models.IntegerField()),
                ('created_dt', models.DateTimeField(default=datetime.datetime.now, null=True)),
                ('updated_dt', models.DateTimeField(default=datetime.datetime.now, null=True)),
                ('course_header', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.Course', to_field='course_header')),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_name', models.CharField(max_length=50, unique=True)),
                ('lesson_description', models.CharField(max_length=100, unique=True)),
                ('lesson_video_link', models.CharField(max_length=50, unique=True)),
                ('lesson_about', models.CharField(max_length=1000)),
                ('created_dt', models.DateTimeField(default=datetime.datetime.now, null=True)),
                ('updated_dt', models.DateTimeField(default=datetime.datetime.now, null=True)),
                ('course_header', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.Course', to_field='course_header')),
            ],
        ),
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faq_id', models.IntegerField()),
                ('question', models.CharField(max_length=50, unique=True)),
                ('answer', models.CharField(max_length=50, unique=True)),
                ('created_dt', models.DateTimeField(default=datetime.datetime.now, null=True)),
                ('updated_dt', models.DateTimeField(default=datetime.datetime.now, null=True)),
                ('course_header', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.Course', to_field='course_header')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_category_id', models.CharField(max_length=50, unique=True)),
                ('course_category_name', models.CharField(max_length=50, unique=True)),
                ('course_category_desc', models.CharField(max_length=5000)),
                ('created_dt', models.DateTimeField(default=datetime.datetime.now, null=True)),
                ('updated_dt', models.DateTimeField(default=datetime.datetime.now, null=True)),
                ('course_header', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.Course', to_field='course_header')),
            ],
        ),
    ]
