# Generated by Django 3.0.3 on 2020-04-30 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.IntegerField()),
                ('course_header', models.CharField(max_length=50, unique=True)),
                ('course_name', models.CharField(max_length=50, unique=True)),
                ('course_category', models.CharField(max_length=50, unique=True)),
                ('course_author', models.CharField(max_length=50, null=True)),
                ('course_description', models.CharField(max_length=5000, null=True)),
                ('course_created_date', models.DateField(null=True)),
                ('course_cupdated_date', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Coursefaq',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faq_id', models.IntegerField()),
                ('course_id', models.IntegerField()),
                ('course_header', models.CharField(max_length=50, unique=True)),
                ('question', models.CharField(max_length=50, unique=True)),
                ('answer', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Coursequality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.IntegerField()),
                ('course_header', models.CharField(max_length=50, unique=True)),
                ('video_quality', models.IntegerField()),
                ('content_quality', models.IntegerField()),
                ('engagging_quality', models.IntegerField()),
                ('fun_quality', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Coursereview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.IntegerField()),
                ('course_header', models.CharField(max_length=50, unique=True)),
                ('rate_awesome', models.IntegerField()),
                ('rate_excelent', models.IntegerField()),
                ('rate_good', models.IntegerField()),
                ('rate_poor', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Coursereviewcomment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_id', models.IntegerField()),
                ('course_id', models.IntegerField()),
                ('course_header', models.CharField(max_length=50, unique=True)),
                ('comment_description', models.CharField(max_length=50, unique=True)),
                ('comment_by', models.CharField(max_length=50, unique=True)),
                ('comment_date', models.DateField(null=True)),
                ('review_ratting', models.CharField(max_length=50, unique=True)),
                ('quality_ratting', models.CharField(max_length=50, unique=True)),
                ('star_rating', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.IntegerField()),
                ('course_header', models.CharField(max_length=50, unique=True)),
                ('lesson_id', models.CharField(max_length=50, unique=True)),
                ('lesson_name', models.CharField(max_length=50, unique=True)),
                ('lesson_description', models.CharField(max_length=5000)),
                ('lesson_video_link', models.CharField(max_length=50, unique=True)),
            ],
        ),
    ]
