# Generated by Django 3.0.3 on 2020-04-30 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Coursefaq',
            new_name='faq',
        ),
        migrations.RenameModel(
            old_name='Coursequality',
            new_name='Quality',
        ),
        migrations.RenameModel(
            old_name='Coursereview',
            new_name='Review',
        ),
    ]
