# Generated by Django 3.0.3 on 2020-04-30 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_auto_20200430_1421'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Coursereviewcomment',
        ),
        migrations.DeleteModel(
            name='Quality',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='rate_awesome',
            new_name='comment_id',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='rate_excelent',
            new_name='star_rating',
        ),
        migrations.RemoveField(
            model_name='review',
            name='rate_good',
        ),
        migrations.RemoveField(
            model_name='review',
            name='rate_poor',
        ),
        migrations.AddField(
            model_name='course',
            name='course_review',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='comment_by',
            field=models.CharField(default='alok', max_length=50, unique=True),
        ),
        migrations.AddField(
            model_name='review',
            name='comment_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='comment_description',
            field=models.CharField(default='alok', max_length=50, unique=True),
        ),
        migrations.AddField(
            model_name='review',
            name='course_content_quality',
            field=models.CharField(default='alok', max_length=50, unique=True),
        ),
        migrations.AddField(
            model_name='review',
            name='course_engagging_quality',
            field=models.CharField(default='alok', max_length=50, unique=True),
        ),
        migrations.AddField(
            model_name='review',
            name='course_review',
            field=models.CharField(default='alok', max_length=50, unique=True),
        ),
        migrations.AddField(
            model_name='review',
            name='course_sound_quality',
            field=models.CharField(default='alok', max_length=50, unique=True),
        ),
        migrations.AddField(
            model_name='review',
            name='course_video_quality',
            field=models.CharField(default='alok', max_length=50, unique=True),
        ),
    ]
