# Generated by Django 3.0.3 on 2020-04-30 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_auto_20200430_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='comment_by',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='comment_description',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='course_content_quality',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='course_engagging_quality',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='course_review',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='course_sound_quality',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='course_video_quality',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
