# Generated by Django 3.0.3 on 2020-05-01 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_remove_course_course_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='course_header',
            field=models.CharField(max_length=50),
        ),
    ]
