# Generated by Django 3.0.3 on 2020-05-01 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_auto_20200501_0757'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.IntegerField()),
                ('course_header', models.CharField(max_length=50, unique=True)),
                ('course_category_id', models.CharField(max_length=50, unique=True)),
                ('course_category_name', models.CharField(max_length=50, unique=True)),
                ('course_category_description', models.CharField(max_length=5000)),
            ],
        ),
    ]
