# Generated by Django 3.0.3 on 2020-05-06 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '00010_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='course_description',
            new_name='course_desc',
        ),
        migrations.AddField(
            model_name='course',
            name='course_short_desc',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
