# Generated by Django 3.0.3 on 2020-05-05 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_auto_20200505_0827'),
    ]

    operations = [
        migrations.RenameField(
            model_name='school',
            old_name='School_about',
            new_name='school_about',
        ),
        migrations.RenameField(
            model_name='school',
            old_name='School_address',
            new_name='school_address',
        ),
        migrations.RenameField(
            model_name='school',
            old_name='School_admission_process',
            new_name='school_admission_process',
        ),
        migrations.RenameField(
            model_name='school',
            old_name='School_board',
            new_name='school_board',
        ),
        migrations.RenameField(
            model_name='school',
            old_name='School_latitude',
            new_name='school_latitude',
        ),
        migrations.RenameField(
            model_name='school',
            old_name='School_longitude',
            new_name='school_longitude',
        ),
        migrations.RenameField(
            model_name='school',
            old_name='School_mailing_address',
            new_name='school_mailing_address',
        ),
        migrations.RenameField(
            model_name='school',
            old_name='School_map_share_link',
            new_name='school_map_share_link',
        ),
        migrations.RenameField(
            model_name='school',
            old_name='School_medium',
            new_name='school_medium',
        ),
        migrations.RenameField(
            model_name='school',
            old_name='School_owned_by',
            new_name='school_owned_by',
        ),
        migrations.RenameField(
            model_name='school',
            old_name='School_phone_number',
            new_name='school_phone_number',
        ),
        migrations.RenameField(
            model_name='school',
            old_name='School_type',
            new_name='school_type',
        ),
        migrations.RenameField(
            model_name='school',
            old_name='School_website_url',
            new_name='school_website_url',
        ),
    ]
