# Generated by Django 3.0.3 on 2020-03-23 15:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('user_name', models.CharField(max_length=50, unique=True)),
                ('phone_number', models.CharField(max_length=17, unique=True, validators=[django.core.validators.RegexValidator(message='phone number is not valid', regex='^\\+?1?\\d{9,15}$')])),
                ('name', models.CharField(max_length=50)),
                ('email_address', models.EmailField(max_length=255, unique=True)),
                ('date_of_birth', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CredentialVarification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50, unique=True)),
                ('phone_number', models.CharField(max_length=50, unique=True)),
                ('Email_varification_code', models.CharField(max_length=200, null=True)),
                ('phone_otp_code', models.IntegerField()),
                ('email_otp_code', models.IntegerField()),
                ('varification_status', models.BooleanField()),
                ('code_sent_counter', models.IntegerField()),
            ],
        ),
    ]
