# Generated by Django 3.0.3 on 2020-05-19 06:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0002_auto_20200519_0601'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(default=123456345602, max_length=17, unique=True, validators=[django.core.validators.RegexValidator(message='phone number is not valid', regex='^\\+?1?\\d{9,15}$')]),
            preserve_default=False,
        ),
    ]
