# Generated by Django 3.0.3 on 2020-04-03 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0005_userprofile_date_of_birth'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='Email_address',
            new_name='email_address',
        ),
    ]
