# Generated by Django 3.0.3 on 2020-04-06 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0007_course'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Course',
            new_name='Post',
        ),
    ]
