# Generated by Django 3.0.3 on 2020-05-01 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0008_auto_20200406_1625'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
