# Generated by Django 3.0.3 on 2020-05-11 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0009_delete_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CredentialVarification',
        ),
        migrations.RemoveField(
            model_name='user',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='user',
            name='email_address',
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
