# Generated by Django 3.0.3 on 2020-05-11 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0010_auto_20200511_0601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.EmailField(max_length=255, unique=True),
        ),
    ]
