# Generated by Django 3.0.3 on 2020-05-11 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0011_auto_20200511_0603'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='username',
            new_name='email_address',
        ),
    ]
